In [1]:
import numpy as np
dataset_filename = "affinity_dataset.txt"
X = np.loadtxt(dataset_filename)
n_samples, n_features = X.shape
print("This dataset has {0} samples and {1} features".format(n_samples, n_features))

This dataset has 100 samples and 5 features


In [2]:
print(X)

[[0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 1. 1. 1.]
 [1. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 1.]
 [1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0.]
 [1. 1. 1. 0. 1.]
 [1. 1. 0. 0. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [1. 1. 0. 1. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 1. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0.

In [3]:
# The names of the features, for your reference.
features = ["bread", "milk", "cheese", "apples", "bananas"]

In [4]:
#X->Y

from collections import defaultdict

valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurences = defaultdict(int)

for sample in X:
    for premise in range(n_features):
        if sample[premise] == 0: continue
        # Record that the premise was bought in another transaction
        num_occurences[premise] += 1
        for conclusion in range(n_features):
            if premise == conclusion:  
                continue
            if sample[conclusion] == 1:
                # This person also bought the conclusion item
                valid_rules[(premise, conclusion)] += 1
            else:
                # This person bought the premise, but not the conclusion
                invalid_rules[(premise, conclusion)] += 1
support = valid_rules
confidence = defaultdict(float)
for premise, conclusion in valid_rules.keys():
    confidence[(premise, conclusion)] = valid_rules[(premise, conclusion)] / num_occurences[premise]

In [5]:
for premise, conclusion in confidence:
    premise_name = features[premise]
    conclusion_name = features[conclusion]
    print("Rule: If a person buys {0} they will also buy {1}".format(premise_name, conclusion_name))
    print(" - Confidence: {0:.3f}".format(confidence[(premise, conclusion)]))
    print(" - Support: {0}".format(support[(premise, conclusion)]))
    print("")

Rule: If a person buys cheese they will also buy apples
 - Confidence: 0.610
 - Support: 25

Rule: If a person buys cheese they will also buy bananas
 - Confidence: 0.659
 - Support: 27

Rule: If a person buys apples they will also buy cheese
 - Confidence: 0.694
 - Support: 25

Rule: If a person buys apples they will also buy bananas
 - Confidence: 0.583
 - Support: 21

Rule: If a person buys bananas they will also buy cheese
 - Confidence: 0.458
 - Support: 27

Rule: If a person buys bananas they will also buy apples
 - Confidence: 0.356
 - Support: 21

Rule: If a person buys bread they will also buy milk
 - Confidence: 0.519
 - Support: 14

Rule: If a person buys bread they will also buy apples
 - Confidence: 0.185
 - Support: 5

Rule: If a person buys milk they will also buy bread
 - Confidence: 0.304
 - Support: 14

Rule: If a person buys milk they will also buy apples
 - Confidence: 0.196
 - Support: 9

Rule: If a person buys apples they will also buy bread
 - Confidence: 0.139
 

In [6]:
#X,Y->Z

from collections import defaultdict

valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurences = defaultdict(int)

for sample in X:
    for premise1 in range(n_features):
        if sample[premise1] == 0: continue
    
        for premise2 in range(n_features):
            if premise1 == premise2:  
                continue
            if sample[premise2] == 1:
                num_occurences[premise1,premise2]+=1
                for conclusion in range(n_features):
                    if premise1 == conclusion or premise2==conclusion: 
                        continue
                    if sample[conclusion] == 1:
                        # This person also bought the conclusion item
                        valid_rules[(premise1,premise2, conclusion)] += 1

                    else:
                        # This person bought the premise, but not the conclusion
                        invalid_rules[(premise1,premise2, conclusion)] += 1
support = valid_rules
confidence = defaultdict(float)
for premise1,premise2, conclusion in valid_rules.keys():
    confidence[(premise1,premise2, conclusion)] = valid_rules[(premise1,premise2, conclusion)] / num_occurences[premise1,premise2]

In [7]:
for premise1, premise2, conclusion in confidence:
    premise_name1 = features[premise1]
    premise_name2 = features[premise2]
    conclusion_name = features[conclusion]
    print("Rule: If a person buys {0},{1} they will also buy {2}".format(premise_name1,premise_name2, conclusion_name))
    print(" - Confidence: {0:.3f}".format(confidence[(premise1,premise2, conclusion)]))
    print(" - Support: {0}".format(support[(premise1,premise2, conclusion)]))
    print("")

Rule: If a person buys cheese,apples they will also buy bananas
 - Confidence: 0.680
 - Support: 17

Rule: If a person buys cheese,bananas they will also buy apples
 - Confidence: 0.630
 - Support: 17

Rule: If a person buys apples,cheese they will also buy bananas
 - Confidence: 0.680
 - Support: 17

Rule: If a person buys apples,bananas they will also buy cheese
 - Confidence: 0.810
 - Support: 17

Rule: If a person buys bananas,cheese they will also buy apples
 - Confidence: 0.630
 - Support: 17

Rule: If a person buys bananas,apples they will also buy cheese
 - Confidence: 0.810
 - Support: 17

Rule: If a person buys bread,milk they will also buy apples
 - Confidence: 0.286
 - Support: 4

Rule: If a person buys bread,apples they will also buy milk
 - Confidence: 0.800
 - Support: 4

Rule: If a person buys milk,bread they will also buy apples
 - Confidence: 0.286
 - Support: 4

Rule: If a person buys milk,apples they will also buy bread
 - Confidence: 0.444
 - Support: 4

Rule: If a

In [8]:
#W,X,Y->Z

from collections import defaultdict

valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurences = defaultdict(int)

for sample in X:
    for premise1 in range(n_features):
        if sample[premise1] == 0: continue
        for premise2 in range(n_features):
            if premise1 == premise2:  
                continue
            if sample[premise2] == 1:
                for premise3 in range(n_features):
                    if premise3 == premise2 or premise3 == premise1: continue
                    if sample[premise3] == 1:
                        num_occurences[premise1,premise2,premise3]+=1
                        for conclusion in range(n_features):
                            if premise1 == conclusion or premise2==conclusion or premise3 == conclusion:  
                                continue
                            if sample[conclusion] == 1:
                                # This person also bought the conclusion item
                                valid_rules[(premise1,premise2,premise3, conclusion)] += 1

                            else:
                                # This person bought the premise, but not the conclusion
                                invalid_rules[(premise1,premise2,premise3, conclusion)] += 1
support = valid_rules
confidence = defaultdict(float)
for premise1,premise2,premise3, conclusion in valid_rules.keys():
    confidence[(premise1,premise2,premise3, conclusion)] = valid_rules[(premise1,premise2,premise3, conclusion)] / num_occurences[premise1,premise2,premise3]

In [9]:
for premise1, premise2,premise3, conclusion in confidence:
    premise_name1 = features[premise1]
    premise_name2 = features[premise2]
    premise_name3 = features[premise3]
    conclusion_name = features[conclusion]
    print("Rule: If a person buys {0}, {1}, {2} they will also buy {3}".format(premise_name1,premise_name2,premise_name3, conclusion_name))
    print(" - Confidence: {0:.3f}".format(confidence[(premise1,premise2,premise3, conclusion)]))
    print(" - Support: {0}".format(support[(premise1,premise2,premise3, conclusion)]))
    print("")

Rule: If a person buys bread, milk, cheese they will also buy bananas
 - Confidence: 1.000
 - Support: 2

Rule: If a person buys bread, milk, bananas they will also buy cheese
 - Confidence: 0.286
 - Support: 2

Rule: If a person buys bread, cheese, milk they will also buy bananas
 - Confidence: 1.000
 - Support: 2

Rule: If a person buys bread, cheese, bananas they will also buy milk
 - Confidence: 0.667
 - Support: 2

Rule: If a person buys bread, bananas, milk they will also buy cheese
 - Confidence: 0.286
 - Support: 2

Rule: If a person buys bread, bananas, cheese they will also buy milk
 - Confidence: 0.667
 - Support: 2

Rule: If a person buys milk, bread, cheese they will also buy bananas
 - Confidence: 1.000
 - Support: 2

Rule: If a person buys milk, bread, bananas they will also buy cheese
 - Confidence: 0.286
 - Support: 2

Rule: If a person buys milk, cheese, bread they will also buy bananas
 - Confidence: 1.000
 - Support: 2

Rule: If a person buys milk, cheese, bananas t

In [10]:
#v,w,x,y=>z

from collections import defaultdict

valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurences = defaultdict(int)

for sample in X:
    for premise1 in range(n_features):
        if sample[premise1] == 0: continue
        for premise2 in range(n_features):
            if premise1 == premise2:  
                continue
            if sample[premise2] == 1:
                for premise3 in range(n_features):
                    if premise3 == premise2 or premise3 == premise1: continue
                    if sample[premise3] == 1:
                        for premise4 in range(n_features):
                            if premise4 ==  premise3 or premise4 == premise2 or premise4==premise1: continue
                            if sample[premise4]==1:
                                num_occurences[premise1,premise2,premise3,premise4]+=1
                                for conclusion in range(n_features):
                                    if premise1 == conclusion or premise2==conclusion or premise3 == conclusion or premise4==conclusion:  
                                        continue
                                    if sample[conclusion] == 1:
                                            # This person also bought the conclusion item
                                        valid_rules[(premise1,premise2,premise3,premise4, conclusion)] += 1
                                    else:
                                            # This person bought the premise, but not the conclusion
                                        invalid_rules[(premise1,premise2,premise3,premise4, conclusion)] += 1
support = valid_rules
confidence = defaultdict(float)
for premise1,premise2,premise3,premise4, conclusion in valid_rules.keys():
    confidence[(premise1,premise2,premise3,premise4, conclusion)] = valid_rules[(premise1,premise2,premise3,premise4, conclusion)] / num_occurences[premise1,premise2,premise3,premise4]

In [11]:
for premise1, premise2,premise3,premise4, conclusion in confidence:
    premise_name1 = features[premise1]
    premise_name2 = features[premise2]
    premise_name3 = features[premise3]
    premise_name4 = features[premise4]
    conclusion_name = features[conclusion]
    print("Rule: If a person buys {0}, {1}, {2}, {3} they will also buy {4}".format(premise_name1,premise_name2,premise_name3,premise_name4, conclusion_name))
    print(" - Confidence: {0:.3f}".format(confidence[(premise1,premise2,premise3,premise4, conclusion)]))
    print(" - Support: {0}".format(support[(premise1,premise2,premise3,premise4, conclusion)]))
    print("")